# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13               # https://pyreadiness.org/3.9/ 
  - sphinx=5.3.0                # https://github.com/conda-forge/sphinx-feedstock
  - invoke=1.7.3                # https://www.pyinvoke.org/changelog.html#{}
  - pyyaml=5.4.1                # https://pyyaml.org/wiki/PyYAML

  # development dependencies
  - black=22.10.0               # https://black.readthedocs.io/en/stable/change_log.html
  - pytest=7.2.0                # https://docs.pytest.org/en/latest/
  - mock=4.0.3                  # https://mock.readthedocs.io/en/latest/
  - pytest-mock==3.10.0          # https://github.com/pytest-dev/pytest-mock

  # PIP dependencies
  - pip=22.1.2                  # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - robotframework-docgen==0.15.0    # https://github.com/robocorp/robotframework-docgen
      - robotframeworklexer==1.1         # https://github.com/robotframework/pygmentslexer
      - inflection==0.5.1                # https://inflection.readthedocs.io/en/latest/#changelog
